In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('new_data/kbo_data.csv')

In [3]:
data[data['이름']=='켈리']

,이름,팀,출장,완투,완봉,선발,승,패,세,홀드,...,삼진,보크,폭투,ERA,FIP,WHIP,ERA+,FIP+,WAR,WPA
86,켈리,15S,30,1,0,29,11,10,0,0,...,139,2,9,4.13,4.19,1.34,117.0,115.8,4.40,-0.13
112,켈리,16S,31,0,0,31,9,8,0,0,...,152,2,8,3.68,4.25,1.32,141.7,122.9,5.95,1.32
142,켈리,17S,30,0,0,30,16,7,0,0,...,189,1,9,3.60,3.69,1.31,139.8,136.9,5.11,1.60
168,켈리,18S,28,0,0,28,12,7,0,0,...,161,2,5,4.09,4.40,1.26,128.5,120.4,3.90,-0.45
191,켈리,19L,29,0,0,29,14,12,0,0,...,126,0,12,2.55,3.46,1.14,160.6,118.6,3.97,2.39
213,켈리,20L,28,1,1,28,15,7,0,0,...,134,0,4,3.32,4.09,1.15,139.4,112.8,4.27,1.64
228,켈리,21L,30,0,0,30,13,8,0,0,...,142,1,7,3.15,3.76,1.24,136.8,115.1,4.97,1.61
253,켈리,22L,27,0,0,27,16,4,0,0,...,153,0,3,2.54,2.95,1.08,156.3,134.7,5.21,3.45